apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app-pod
  #namespace: dev
  labels:
    app: mongo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app-pod
        image: eagunuworld/mongodb-springboot-app:BUILD_TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-app
  #namespace: dev
spec:
  selector:
    app: mongo-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30022
  type: NodePort
