apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod 
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: eagunuworld/mongodb-springboot-app:BUILD_TAG
        ports:
        - containerPort: 8080
